### ISSUE TITLE
Your values/strings.xml is not in English

### ISSUE THREAD

**Issue by CytoDev** [Kamshak/BrainPhaser#48]
Hey there, I stumbled upon your repo after browsing @ordago's (cloned) repositories. I am opening this issue for a couple of reasons, but I will attempt to fix them while I write this issue.

Leaving your original `strings.xml` file in German can have a very negative impact on the user experience of your application (see [this](https://developer.android.com/training/basics/supporting-devices/languages.html#CreateDirs) article about it).

Also, not to bash on @ordago, but some of the translations in `strings-en.xml` are too generic or should use other words when you read them. I'm guessing he is Spanish since he translated my app to it, so it's not a big deal.

You can see a pull request with my name on it within the next few minutes.

**Comment by ordago** [comment]
Hi @CytoDev, I had the files translated by a company since I don't know German.

Yours I translated myself.

**Comment by CytoDev** [comment]
@ordago, doesn't matter who translated them, some of them where too literal. Hope you didn't pay them a lot though.

**Comment by Kamshak** [comment]
Somehow the merge didn't close this, closing this manually.

**Comment by ordago** [comment]
@CytoDev I understand. I checked the changes you did and I agree with them. 

I will have to edit the Spanish file to match the changes because it had a similar *style*. But I'll will have to be in a week after I come back from the Netherlands.

I didn't pay anything, it was a test run.

**Comment by CytoDev** [comment]
@ordago Funny, I live in The Netherlands... Can I inquire what you're doing there this weekend? A festival perhaps? Like I don't know, let's say Defqon.1?

**Comment by ordago** [comment]
I'm visiting family and doing tourism. I'll be in Rotterdam mostly, and will hop to Amsterdam a day or two. No festivals.

**Comment by CytoDev** [comment]
@ordago Cool, I wish you a great time nonetheless.

**Comment by ordago** [comment]
Thanks :)
