### ISSUE TITLE
Issues with Build

### ISSUE THREAD

**Issue by Kamshak** [Kamshak/BrainPhaser#50]
@CytoDev @ordago could you give me some info on troubles you were having with the build? Would like to fix these to allow easy adaption/customization of the app. I know documentation is very sparse at the moment - would love to improve.

**Comment by ordago** [comment]
Without touching anything I got a compile error when I tried to run the app. I took a screenshot of the error.

I'm away from my computer. I'll post the screenshot later.

**Comment by CytoDev** [comment]
@Kamshak I experienced some errors yesterday evening, those errors where along the lines of some gradle file being either missing or having incorrect dependencies.

**Comment by Prale** [comment]
Hi Gents do you have documentation for the project yet, there are some components i need an explanation on.

Thanks in advance

**Comment by Kamshak** [comment]
Thanks Cyto, was on holiday for a few days will apply your suggestions :)
@Prale: Currently only the (German) Javadoc but i'd be happy to add some explanations - what specifically needs explanation?

**Comment by Prale** [comment]
Thanks for the response, some of the issues I have figured a way out for now. Wanted to know what method/application you used to create your bpc files?

**Comment by Kamshak** [comment]
These are manually written. No documentation for the format other than the example file exists although valid combination is covered in it.
