### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [Kamshak/BrainPhaser#54]
Hi @Kamshak 

Since Brain Phaser is licensed under GNU GPL v3, can you consider adding this app to the F-Droid repository?
I can give you documentation and links if you need it ;)

**Comment by ValentinFunk** [comment]
Sure, that's a good idea! If you could link me that'd be great :+1:

**Comment by Poussinou** [comment]
So first of all, be sure there is no proprietary binary or library in your app. If this is the case, you must replace them, or be sure that the app builds without them.
Then you can read the [inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy), submit [your app](https://gitlab.com/fdroid/rfp/issues). If you have the skills, you can better do a Pull Request with your app and the metadatas. There is a big big manual [here](https://f-droid.org/docs/) and a more interesting one [here](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/)

If you're lost, just open an issue on their gitlab repo, they will help you but it will take more time ;)
