### ISSUE TITLE
Adding images to challenges

### ISSUE THREAD

**Issue by manuchopra** [Kamshak/BrainPhaser#56]
Hi! I am very new to Android development and I was wondering how I could add images to the challenges? So something like "What is the object in the image below?", followed by an image and then followed by 4 multiple choice options. I understand that I would need to add an ImageView but would appreciate some guidance! 

Would really appreciate your help!

**Comment by manuchopra** [comment]
Figured it out! Thanks :)

**Comment by ValentinFunk** [comment]
Hi! Glad to see that you've found this app :)

What you want to do is add a new Challenge Type. The way this is implemented in Brain Phaser is like this:

1) The ChallengeActivity is responsible for displaying challenges and progress. It's the screen you see when answering a challenge.
2) Inside of the ChallengeActivity, a Fragment is mounted. Each Challenge Type has it's own Fragment that e.g. tells the activity if the user was correct or wrong. 
3) Create a challenge type here (links the id, color and name for UI): [ChallengeType](https://github.com/Kamshak/BrainPhaser/blob/master/app/src/main/java/de/fhdw/ergoholics/brainphaser/database/ChallengeType.java#L10)
4) All Challenge Types are registered inside the [AnswerFragmentFactory](https://github.com/Kamshak/BrainPhaser/blob/master/app/src/main/java/de/fhdw/ergoholics/brainphaser/activities/playchallenge/AnswerFragmentFactory.java#L19) and extend [AnswerFragment](https://github.com/Kamshak/BrainPhaser/blob/master/app/src/main/java/de/fhdw/ergoholics/brainphaser/activities/playchallenge/AnswerFragment.java)

Hope this helps :)

**Comment by ValentinFunk** [comment]
Haha you just closed this while I was typing :) Glad you figured it out :+1: 
If you'd like to add your solution to the repo I'd be happy to take a look at a PR

**Comment by manuchopra** [comment]
For sure! Will definitely do that! 

Thanks,
Manu
